name:                yaminabe
version:             0.1.0.0
github:              "yourusername/yaminabe"
license:             BSD3
author:              "Your Name"
maintainer:          "youremail@example.com"
copyright:           "2021 Your Name"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yourusername/yaminabe#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  yaminabe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yaminabe

tests:
  yaminabe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yaminabe
